"""add gift money table

Revision ID: 3727894c95f8
Revises: b92ed265d8c2
Create Date: 2026-09-06 14:43:12.637936

"""
from alembic import op
import sqlalchemy as sa


revision = '3727894c95f8'
down_revision = 'b92ed265d8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_money',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('type', sa.Enum('wedding', 'sick', 'newborn', name='giftmoneytype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_money_id'), 'gift_money', ['id'], unique=False)
    op.create_index(op.f('ix_gift_money_user_id'), 'gift_money', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gift_money_user_id'), table_name='gift_money')
    op.drop_index(op.f('ix_gift_money_id'), table_name='gift_money')
    op.drop_table('gift_money')
    # ### end Alembic commands ###
